name: Deploy 2048 Game to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81F317DB2E6348B2A4CBEFF1E07D2C52 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D6C069ABE03F4D2A8D9E8E4E2FEED439 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DAD3A20C50941C7884564DA712153F9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: RG-2048Game
          slot-name: Production
          package: .
